### ISSUE TITLE
Compatibility with PerfectPixel addon?

### ISSUE THREAD

**Issue by kexes** [mtking2/eso-font-changer#1]
I know its not your responsibility, but you wrote at the Font Changer addon on ESOUI site that you can look into the PP support if anyone need to.

So here is the thing:

I tried the original Font Changer PP version first, but i had .lua errors with it which i think caused by another addon called the [Bandit User Interface](https://www.esoui.com/downloads/info1643-BanditsUserInterface.html#info) which also im using (posted the error logs on the [ESOUI site](https://www.esoui.com/downloads/info3728-FontChanger.html#comments)), so i tried your forked version and its working without any issues or any .lua errors, except that some elements of the whole UI system are still using the default ESO font type instead of the new ones. When i disable the PP addon the UI will start using the new fonts where its not there before, so im sure your fork just needs the proper support for PP.

Here are some example screenshots:

![interact](https://github.com/mtking2/eso-font-changer/assets/59803900/2e030f41-2bc0-4dc2-9766-25264f2f6e7a)
![inventory](https://github.com/mtking2/eso-font-changer/assets/59803900/4e4f33d8-6398-461d-868f-d31fc660d247)
![quests](https://github.com/mtking2/eso-font-changer/assets/59803900/7642d312-6e56-416e-9a8f-b3ec0467f04a)
![skills](https://github.com/mtking2/eso-font-changer/assets/59803900/695066f5-be0d-4172-8f29-e2ddd1ed7d2d)

**Comment by mtking2** [comment]
@kexes I'm working on adding support for these. Thank you for these screenshots! They are super helpful.

I think I've gotten PerfectPixel working great so far and I hope to find some time soon to work on Bandits UI.

PR: #2

**Comment by mtking2** [comment]
@kexes no issues with Bandits UI!

Here is [v1.5](https://github.com/mtking2/eso-font-changer/releases/tag/v1.5)

Bandits UI has its own font settings so I am not going to try to put any overrides on it for now.
